-- Customer Shopping Behavior Analysis Project


-- Q1. What is the total revenue generated by male vs female customers?

SELECT Gender, SUM(`Purchase Amount`) AS total_revenue
FROM customers
GROUP BY Gender;



-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT `Customer ID`, `Purchase Amount`
FROM customers
WHERE `Discount Applied` = 'Yes'
AND `Purchase Amount` > (SELECT AVG(`Purchase Amount`) FROM customers);



-- Q3. Which are the top 5 products with the highest average review rating?

SELECT `Item Purchased`, AVG(`Review Rating`) AS avg_rating
FROM customers
GROUP BY `Item Purchased`
ORDER BY avg_rating DESC
LIMIT 5;



-- Q4. Compare the average purchase amounts between Standard and Express Shipping.

SELECT `Shipping Type`, AVG(`Purchase Amount`) AS avg_purchase
FROM customers
GROUP BY `Shipping Type`;



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue.

SELECT `Subscription Status`,
AVG(`Purchase Amount`) AS avg_spend,
SUM(`Purchase Amount`) AS total_revenue
FROM customers
GROUP BY `Subscription Status`;



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT `Item Purchased`,
COUNT(CASE WHEN `Discount Applied` = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customers
GROUP BY `Item Purchased`
ORDER BY discount_percentage DESC
LIMIT 5;



-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.

SELECT 
CASE 
    WHEN `Previous Purchases` = 0 THEN 'New'
    WHEN `Previous Purchases` BETWEEN 1 AND 3 THEN 'Returning'
    ELSE 'Loyal'
END AS Customer_Segment,
COUNT(*) AS total_customers
FROM customers
GROUP BY Customer_Segment;



-- Q8. What are the top 3 most purchased products within each category?

SELECT Category, `Item Purchased`, purchase_count
FROM (
    SELECT Category, `Item Purchased`,
    COUNT(*) AS purchase_count,
    RANK() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS rnk
    FROM customers
    GROUP BY Category, `Item Purchased`
) ranked_products
WHERE rnk <= 3;



-- Q9. Are customers who are repeat buyers (more than 3 previous purchases) also likely to subscribe?

SELECT `Subscription Status`, COUNT(*) AS total_customers
FROM customers
WHERE `Previous Purchases` > 3
GROUP BY `Subscription Status`;



-- Q10. What is the revenue contribution of each age group?

Age_Group_Final =
SWITCH(
TRUE(),
[Age] <= 31, "Young Adult",
[Age] <= 44, "Adult",
[Age] <= 57, "Middle-aged",
"Senior"
)